INSERT INTO company VALUES('FORTUM', 'FINLAND', 'Fortum');
INSERT INTO company VALUES('SAMPO', 'FINLAND', 'Sampo');
INSERT INTO company VALUES('PFE', 'AMERICA', 'Pfizer');
INSERT INTO company VALUES('GILD', 'AMERICA', 'Gilead');
INSERT INTO company VALUES('BABA', 'CHINA', 'ALIBABA');
INSERT INTO stockexchange VALUES('NYSE', 'New York Stock Exchange', 'AMERICA');
INSERT INTO stockexchange VALUES('NASDAQ', 'NASDAQ Stock Exchange', 'AMERICA');
INSERT INTO stockexchange VALUES('HEL', 'NASDAQ:Helsinki Stock Exchange', 'AMERICA');
INSERT INTO stockexchange VALUES('HKG', 'Hong Kong Stock Exchange', 'HONG_KONG');
INSERT INTO equity VALUES(1, 'FORTUM', 'FORTUM', 'HEL');
INSERT INTO equity VALUES(2, 'GILD', 'GILD', 'NYSE');
INSERT INTO equity VALUES(3, 'BABA', 'BABA', 'NYSE');
INSERT INTO equity VALUES(4, '9988', 'BABA', 'HKG');