FROM jboss/wildfly
COPY target/security-search-engine-1.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/
ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone.xml", "-Djboss.http.port=8082", "-Dapikey=${apikey}", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
